name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  tests_latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: docker compose run --rm v -N -W test .

  tests_0-4-11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test (v0.4.11)
        run: docker compose run --rm v0411 -N -W test .

  tests_0-4-10:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test (v0.4.10)
        run: docker compose run --rm v0410 -N -W test .

  tests_0-4-9:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test (v0.4.9)
        run: docker compose run --rm v049 test .

  tests_0-4-8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test (v0.4.8)
        run: docker compose run --rm v048 test .
